## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
app_type_counts = application_df['APPLICATION_TYPE'].value_counts()
app_type_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
# Chose cutoff value 500
application_types_to_replace = list(app_type_counts[app_type_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
# Select the values with counts greater than 1
classifications_1 = classification_counts[classification_counts > 1]

# Print the selected values
classifications_1

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
columns_to_encode = ['APPLICATION_TYPE',	'AFFILIATION', 'CLASSIFICATION', 'INCOME_AMT', 'USE_CASE', 'ORGANIZATION', 'SPECIAL_CONSIDERATIONS']
app_dummies = pd.get_dummies(application_df, columns=columns_to_encode, dtype=int)
app_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,1,1,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,1,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,1,1,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,1,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,1,1,0

In [10]:
app_dummies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 44 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   STATUS                        34299 non-null  int64
 1   ASK_AMT                       34299 non-null  int64
 2   IS_SUCCESSFUL                 34299 non-null  int64
 3   APPLICATION_TYPE_Other        34299 non-null  int64
 4   APPLICATION_TYPE_T10          34299 non-null  int64
 5   APPLICATION_TYPE_T19          34299 non-null  int64
 6   APPLICATION_TYPE_T3           34299 non-null  int64
 7   APPLICATION_TYPE_T4           34299 non-null  int64
 8   APPLICATION_TYPE_T5           34299 non-null  int64
 9   APPLICATION_TYPE_T6           34299 non-null  int64
 10  APPLICATION_TYPE_T7           34299 non-null  int64
 11  APPLICATION_TYPE_T8           34299 non-null  int64
 12  AFFILIATION_CompanySponsored  34299 non-null  int64
 13  AFFILIATION_Family/Parent     34299 non-null  int64
 14  AFFILIATION_Independent       34299 non-null  int64
 15  AFFILIATION_National          34299 non-null  int64
 16  AFFILIATION_Other             34299 non-null  int64
 17  AFFILIATION_Regional          34299 non-null  int64
 18  CLASSIFICATION_C1000          34299 non-null  int64
 19  CLASSIFICATION_C1200          34299 non-null  int64
 20  CLASSIFICATION_C2000          34299 non-null  int64
 21  CLASSIFICATION_C2100          34299 non-null  int64
 22  CLASSIFICATION_C3000          34299 non-null  int64
 23  CLASSIFICATION_Other          34299 non-null  int64
 24  INCOME_AMT_0                  34299 non-null  int64
 25  INCOME_AMT_1-9999             34299 non-null  int64
 26  INCOME_AMT_10000-24999        34299 non-null  int64
 27  INCOME_AMT_100000-499999      34299 non-null  int64
 28  INCOME_AMT_10M-50M            34299 non-null  int64
 29  INCOME_AMT_1M-5M              34299 non-null  int64
 30  INCOME_AMT_25000-99999        34299 non-null  int64
 31  INCOME_AMT_50M+               34299 non-null  int64
 32  INCOME_AMT_5M-10M             34299 non-null  int64
 33  USE_CASE_CommunityServ        34299 non-null  int64
 34  USE_CASE_Heathcare            34299 non-null  int64
 35  USE_CASE_Other                34299 non-null  int64
 36  USE_CASE_Preservation         34299 non-null  int64
 37  USE_CASE_ProductDev           34299 non-null  int64
 38  ORGANIZATION_Association      34299 non-null  int64
 39  ORGANIZATION_Co-operative     34299 non-null  int64
 40  ORGANIZATION_Corporation      34299 non-null  int64
 41  ORGANIZATION_Trust            34299 non-null  int64
 42  SPECIAL_CONSIDERATIONS_N      34299 non-null  int64
 43  SPECIAL_CONSIDERATIONS_Y      34299 non-null  int64
dtypes: int64(44)
memory usage: 11.5 MB

In [11]:
# Split our preprocessed data into our features and target arrays
X = app_dummies.drop(['IS_SUCCESSFUL'], axis=1).values
y = app_dummies['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  80
hidden_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [15]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 10s 7ms/step - loss: 0.5707 - accuracy: 0.7211
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5544 - accuracy: 0.7299
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5519 - accuracy: 0.7310
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5501 - accuracy: 0.7297
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5490 - accuracy: 0.7322
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5484 - accuracy: 0.7322
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7336
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7327
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7330
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5460 - accuracy: 0.7345
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7338
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7350
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7344
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7341
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7352
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7350
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7362
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7343
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5431 - accuracy: 0.7354
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7368
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7349
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7367
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7357
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7362
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7365
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7379
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7378
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7372
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7367
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7357
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7363
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7378
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7376
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7370
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7370
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7378
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7371
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7385
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7371
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7377
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7382
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7381
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7376
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7378
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7390
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7374
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7377
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7393
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7378
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7381
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7381
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7377
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7376
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7384
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7391
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7389
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7379
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7379
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7381
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7395
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7382
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7381
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7383
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7388
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7399
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7395
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7392
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7389
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7390
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7384
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7399
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7389
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7385
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7395
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7395
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7389
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7406
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7398
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7386
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7388
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7390
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7393
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7386
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7397
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7395
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7409
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7402
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7390
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7398
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7395
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7393
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7399
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7393
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7392
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7394
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7394
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7396
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7389
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7400
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7395

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5558 - accuracy: 0.7297 - 550ms/epoch - 2ms/step
Loss: 0.5558062195777893, Accuracy: 0.72967928647995

In [17]:
# Export our model to HDF5 file  Per Justin: modelname.save('file name to save.h5')
nn.save('AlphabetSoupCharity.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(